---
galaxy_info:
  role_name: gitlab_hierarchy
  author: q.sallio@gmail.com
  description: >-
    Declarative management of GitLab groups, subgroups, and projects from a simple YAML structure.
  company: ""
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - gitlab
    - scm
    - groups
    - projects
    - hierarchy
    - ansible
    - infrastructure
    - open-source
    - python
    - api
